version: '3'
services:
  web:
    build: .
    ports:
        - "5000:80"
    labels:
        - traefik.http.routers.NOM-SERVICE-https.entrypoints=secure
        - traefik.http.routers.NOM-SERVICE-https.rule=Host(`NOM-SERVICE.NDD`)
        - traefik.http.routers.NOM-SERVICE-https.tls=true
        - traefik.http.routers.NOM-SERVICE-https.tls.certresolver=letsencrypt
