version: '3'
services:
  web:
    build: .
    ports:
        - "5000:80"
    networks:
        - proxy
    labels:
        - traefik.frontend.rule=Host:openincubator.tech

networks:
  proxy:
    external:
      name: "traefik-net"
